support for youtube music
GabrielDuarteM/webplayer-hotkeys pull request #61
Opened 2018-12-17 16:48 UTC by shakhraj

Added support for YouTube Music

Manifest change is not required as permission for `*.youtube.com` was already present

2018-12-22 15:29 UTC, GabeDuarteM requested changes
Thank you for this PR!

Just added some comments, could you please check?

2018-12-22 15:29 UTC, GabeDuarteM commented on src/background.ts
> +    tabQuery: '*://music.youtube.com/',
I think here the URL should end with a wildcard, otherwise, the extension will only load when you are on the main page.
```suggestion
    tabQuery: '*://music.youtube.com/*',
```

2018-12-24 09:45 UTC, GabeDuarteM approved these changes

2018-12-24 09:46 UTC, GabrielDuarteM commented
LGTM, thanks!

2018-12-24 09:46 UTC, merged

2018-12-24 09:50 UTC, GabrielDuarteM commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [Chrome Web Store](https://chrome.google.com/webstore/detail/ikmkicnmahfdilneilgibeppbnolgkaf)
- [GitHub release](https://github.com/GabrielDuarteM/webplayer-hotkeys/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2018-12-24 09:53 UTC, shakhraj commented
thank you!